name: SkellyTracker Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'skellytracker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: System Info
        run: |
          uname -a || true
          lsb_release -a || true
          gcc --version || true
          env
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "-e.[all]"
      - name: Fix OpenCV conflict
        run: |
          pip uninstall -y opencv-python opencv-contrib-python
          pip install opencv-contrib-python==4.8.1.78
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/skellytracker" >> $GITHUB_ENV
      - name: Run Tests with Pytest
        run: |
          pip install pytest
          pytest skellytracker/tests